server:
  port: 8080

#Actuator
management:
  server:
    port: 9000
    address: 127.0.0.1

#MariaDB
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ROPPA
    username: roppa
    password: r0ppa!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

---
